#!/usr/bin/env bash
#
# Clone every Vibrant Gio repository as a sibling of this one, then generate
# go.work from what is actually present.
#
# The working tree mirrors the organization: one directory per repository,
# all siblings, .github among them rather than above them. The parent
# directory — the workspace root — is not a repository at all; it is just
# the folder the org is checked out into. G0E.1 is where this shape landed;
# before that .github was simultaneously the root and the parent, with the
# twenty siblings hidden under a gitignored .repos/.
#
# go.work is generated, never committed. A workspace describes one
# developer's checkout, so it is derived from the go.mod files actually on
# disk: a repository you have not cloned is simply absent from the
# workspace, rather than a dangling `use` line. Re-run this script after
# cloning or removing a repository.
#
# The whole set is cloned every time, not a subset. What this plan edits is
# the module graph, and no task can see an edge whose other end is missing.
#
# Plain git over https: gh is not assumed to be installed.

set -euo pipefail

# Workspace root: the parent of the .github checkout this script lives in.
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

# The stack, bottom to top.
STACK=(mvu theme components effects patterns markdown)

# Leaf libraries: typography, drawing helpers.
LEAVES=(font style textdraw backdrop gradient circle)

# Support libraries — consumed by the design system, never dependent on it.
SUPPORT=(ivg svg seen csg kiwi noise traer)

# Applications — and design, the published bundle: like the applications it
# sits at the top of the stack, imported by nothing.
APPS=(workbench design)

REPOS=("${STACK[@]}" "${LEAVES[@]}" "${SUPPORT[@]}" "${APPS[@]}")

for name in "${REPOS[@]}"; do
	if [ -d "$name/.git" ]; then
		printf 'pull  %s\n' "$name"
		git -C "$name" pull --ff-only --quiet
	else
		printf 'clone %s\n' "$name"
		git clone --quiet "https://github.com/vibrantgio/$name.git" "$name"
	fi
done

# Generate go.work from the modules actually present. The `go` directive
# must match the members' language version exactly — not the toolchain's —
# or the workspace builds under different semantics than GOWORK=off, which
# is what CI and every consumer see. It is read from the members and the
# script refuses to guess if they disagree.
modules=$(find . -mindepth 2 -name go.mod -not -path '*/.git/*' -not -path './.github/*' |
	sed 's|/go.mod$||; s|^\./||' | sort)

govers=$(for m in $modules; do sed -n 's/^go //p' "$m/go.mod"; done | sort -u)
if [ "$(printf '%s\n' "$govers" | wc -l | tr -d ' ')" != 1 ]; then
	echo "error: members disagree on their go directive:" >&2
	printf '%s\n' "$govers" >&2
	exit 1
fi

{
	echo "// Generated by scripts/clone-all.sh from the go.mod files present in"
	echo "// this checkout — regenerate rather than edit, and never commit it:"
	echo "// a workspace describes one developer's checkout, nothing shareable."
	echo "//"
	echo "// No member may carry a \`replace\` directive: committed in a public"
	echo "// module, it breaks every consumer outside this tree."
	echo "// scripts/check-no-workspace.sh enforces both halves."
	echo
	echo "go $govers"
	echo
	echo "use ("
	for m in $modules; do
		echo "	./$m"
	done
	echo ")"
} >go.work

printf '\n%d repositories, %d workspace members (go %s)\n' \
	"$(find . -maxdepth 2 -name .git -type d | wc -l | tr -d ' ')" \
	"$(printf '%s\n' "$modules" | wc -l | tr -d ' ')" \
	"$govers"
